### ISSUE TITLE
#Errors to be corrected from Convetions and best practices used at nezago

### ISSUE THREAD

**Issue by patsicko** [descholario/nezago-guidelines#6]
1. Worldwide in one word not ~~world wide~~ as if it is two words
1. Separated by not ~~separted by~~ 
1. on Readme file template, author, correct other one who not ~~whou~~

**Comment by descholar-ceo** [comment]
Thank you dear @patsicko for submitting this issue, please review all of the documents, and add more rooms for improvements on this issue, and then I will open a Pull Request to fix all of them

**Comment by Ituze1** [comment]
my pleasure
